sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -f Dockerfile.dev -t test .
script:
    - docker run -e CI=true test npm run test
deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: docker-practice
    env: Dockerpractice-env
    bucket_name: "elasticbeanstalk-us-east-2-178987093064"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id:
        secure: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
